apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nita
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-home
  name: jenkins-home
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
