apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nita
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
