apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: nita
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
