kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: nita
  name: pv-volume
  labels:
      type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydatai2"
